title: Lindsay Bittinger
author: Lindsay Bittinger
email: lindsaybittinger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a lover of ideas and a master of execution.

github_username:  bittingerl # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
